FROM node:16 AS builder

WORKDIR /app

COPY . .

RUN npm install

ENV REACT_APP_API_URL=https://api.example.com

RUN npm run build

# ----------- Stage 2: Serve with Nginx -------------
FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /usr/share/nginx/html

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 80
